import java.until.Scanner;
public class TUGAS{
    public static void main (String[] args){
        Scanner input = new Scanner (System.in);
        
        System out.println("masukkan nilai struktur data : ");
        double strukturData = ns.nextDouble();

        System.out.println("masukkan nilai pemrograman berorientasi objek : ");
        double pemrogramanBerorientasiObjek = input.nextDouble();

        
        System.out.println("masukkan nilai basis data : ");
        double basisData = input.nextDouble();

        System.out.println("algoritma dan pemrograman : ");
        double algoritmaDanPemrograman = input.nextDouble();
        
        
    }
        
        
    }

}