import java.until.Scanner;
public class TUGAS{
    public static void main (String[] args){
        Scanner input = new Scanner (System.in);
        
        System out.println("masukkan nilai struktur data : ");
        double strukturData = ns.nextDouble();

        System out.println("masukkan nilai pemrograman berorientasi objek : ");
        double pemrogramanBerorientasiObjek = ns.nextDouble();

        
        
    }

}